# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Earl Academy
tagline:          Ex thea, scientia
description:      "A collection of tutorials, reference materials and articles on the use of Earl Grey, a compile-to-js language."
url:              https://madcapjake.github.io/earl-academy
baseurl:          /earl-academy/

author:
  name:           'Jake Russo'
  url:            https://madcapjake.github.io

paginate:         5

exclude:          [vendor]

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/madcapjake/earl-academy
